name: Run Tests for practice-ci-cd-web

on:
  push:
    branches:
      - main
      - dev

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x  # Node.js 버전을 설정
          
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Google Chrome Driver
        run: |
          npm install chromedriver

      - name: Debug Chrome and ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Install Dependencies for Test Code
        run: |
          python -m pip install --upgrade pip
          pip install -r test-code/requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13  # Python 버전 설정

      - name: Checkout Test Code for practice-ci-cd-web
        uses: actions/checkout@v3
        with:
          repository: lovefreeUnity/-Test-practice-ci-cd-web
          path: test-code

      # 테스트코드 작성 때 로컬에서 돌렸기에 여기서도 로컬 웹 동작
      - name: Checkout practice-ci-cd-web web
        uses: actions/checkout@v3
        with:
          repository: lovefreeUnity/practice-ci-cd-web
          ref: main

      - name: Start Test Web
        run: npm run dev &
        env:
          HOST: 127.0.0.1
          PORT: 8080  # 앱이 실행될 포트 (설정 필요)

      - name: Run Tests for practice-ci-cd-web
        run: python test-code/testcode.py  # 테스트 실행 명령
